#ifndef COMMONS
#define COMMONS

enum HAND_ACTION { ZOOM, ROTATE, PAN };

enum ZOOML_TYPE {ZOOM_IN, ZOOM_OUT};

enum ROTATE_DIRECTION {ROTATE_XY, ROTATE_YZ, ROTATE_XZ};

enum PAN_DIRECTION {PAN_LEFT, PAN_RIGHT, PAN_UP, PAN_DOWN};

#endif // COMMONS

